version: "3.3"
services:
  mysqlservice:
    image: mysql:5.5
    container_name: mysql-container
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    ports:
      - 27017:27017

  authenticationservice:
    container_name: user-authentication-service
    build: authenticationservice/
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice
      - cloudapiservice
      - eurekaServer
    restart: always

  movieservice:
    container_name: user-vehicle-service
    build: VehicleService/
    network_mode: host
    ports:
      - 8081:8081
    depends_on:
      - mongodbservice
      - cloudapiservice
      - eurekaServer
    restart: always

  MovieFavouriteService:
      container_name: movie-favourite-service
      build: VehicleService/
      network_mode: host
      ports:
        - 8082:8082
      depends_on:
        - mongodbservice
        - cloudapiservice
        - eurekaServer
      restart: always

  cloudapiservice:
    image: cloud-api-service
    build: SpringCloudAPIGateway/
    restart: always
    network_mode: host
    #hostname: localhost
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eurekaServer

  eurekaServer:
    image: eureka-service
    build: EurekaServer/
    restart: always
    network_mode: host
    #hostname: localhost
    environment:
      EUREKA_SERVER_PORT: 8761
    ports:
      - 8761:8761